name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Java 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Node 14
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install Cordova
      run: npm install -g cordova@11.0.0

    - name: Build Project
      run: |
        cordova create app_build com.gachalove.app GachaLove
        cd app_build
        # Usamos una plataforma más vieja para que sea compatible con Java 8
        cordova platform add android@10.1.1
        rm -rf www
        cp -r ../www .
        [ -f ../config.xml ] && cp ../config.xml .
        cordova build android --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: GachaLove-APK
        path: app_build/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
